### ISSUE TITLE
Déplacer fichier source "Guide documentation portail SNIIRAM"

### ISSUE THREAD

**Issue by AnneC-inds** [indsante/Documentation-SNDS#12]
Proposition :
Déplacer le fichier source "Guide documentation portail SNIIRAM" au même endroit que la **page** "Guide documentation portail SNIIRAM" et le faire sortir de la partie "Ressources" : ajouter un lien de téléchargement en dessous du titre ?

**Comment by pajachiet** [comment]
Résolu https://github.com/indsante/Documentation-SNDS/pull/13
