### ISSUE TITLE
Proposition : Utiliser gitlab.com plutôt que github.com

### ISSUE THREAD

**Issue by pajachiet** [indsante/Documentation-SNDS#19]
## Proposition

La proposition est de migrer sur gitlab.com en remplacement de github.com.

Cette proposition a été faite indépendamment par 2 personnes lors du Meetup SNDS #1. 

## Détails

Le principal argument pour ce changement est que **GitHub est un logiciel privé**, racheté par Microsoft. 
Tandis que **GitLab a un cœur communautaire open-source** (GitLab CE), et des fonctionnalités entreprises supplémentaires propriétaires (GitLab EE) - cf [cette page](https://about.gitlab.com/install/ce-or-ee/). 

En conséquence
- Il est possible d'installer GitLab sur son propre serveur.
- Il sera bien plus facile de partir de gitlab.com si une évolution ne nous convient pas (fermeture du service, tarif) que de github.com
  - Il est par exemple possible de contribuer à la [traduction de GitLab](https://translate.gitlab.com/) en français, tandis que GitHub a décidé de ne plus maintenir de langage autre que l'anglais [depuis 2016](https://github.blog/2010-07-13-github-in-your-language/).

Pour cette raison, **GitLab est un choix fréquents dans les administrations**, sur un serveur interne ou sur gitlab.com (a minima 80 personnes à la DREES, la HAS, d'autres certainement). 
Les utilisateurs de ces administratiosn connaissent donc déjà l'interface GitLab. De plus, ceux qui utilisent gitlab.com ont **déjà un compte sur gitlab.com**, ce qui facilitera les contributions.

La comparaison des fonctionnalités et des interfaces sera difficile. C'est en partie une question d'habitude (je suis personnellement plus habitué et préfère GitLab). Les 2 plateformes ont des logiques proches, avec des spécificités tout de même importantes. 

En général, GitHub est plus utilisé, donc plus de services tierces sont bien intégrés à GitHub. En contrepartie, GitLab a développé des fonctionnalités internes, plutôt que de devoir recourir à ces services tierces. L'intégration continue de GitLab est par exemple d'excellente qualité, ce qui nous permettra d'ajouter facilement des opérations automatiques sur la documentation via des scripts.

Pour notre cas d'usage, on notera tout de même **un fort argument en faveur de GitLab : l'éditeur web** (Web IDE).
- Comme sur GitHub, il est possible d'éditer un fichier seul. 
- L'éditeur web permet également de naviguer et d'éditer l'ensemble des fichiers, avec leur arborescence. Cela permettra vraiment d'éditer le contenu de la documentation-snds en ligne, ce qui reste assez maladroit et pénible avec GitHub, où il faut faire un commit par fichier à éditer, en revenant sur la branche en question entre les commits.

Un micro-argument en faveur de gitlab.com, c'est que l'utilisateur _inds_ n'est pas encore pris. Il sera donc plus facile de retrouver les dépôts sur gitlab.com.

Le principal argument en faveur de GitHub est que la communauté est plus importante. Je pense que l'argument ne tient plus si l'on se concentre sur *notre* communauté d'utilisateur du SNDS (qui n'a majoritairement pas encore utilisé ni l'un ni l'autre). D'autant que les profils développeurs déjà présents sur GitHub auront peu de difficulté à passer sur GitLab, en comparaison de la difficulté pour les utilisateurs non développeurs à éditer la documentation en ligne.

Un autre argument en faveur de GitHub est que nous sommes déjà partis dessus. C'est un vrai argument, et pourquoi il est important de vraiment trancher cette question rapidement. Il est encore tout à fait temps vu que les contributeurs de la DREES ont déjà un compte sur GitLab, que l'INDS n'aurait que 2 comptes à migrer, et que nous n'avons encore formé personne à GitHub.

## Proposition alternative

Une proposition alternative, par un membre du meetup, serait d'utiliser framagit.org. 
- L'avantage serait d'être sur une vrai version communautaire open source, et de soutenir la communauté framasoft.
- L'inconvénient est que nous avons moins de garantie sur la fiabilité du système, sur sa pérennité et le fait qu'il tienne la charge (il y a peu de runner partagés par exemple pour l'intégration continue). 
De plus, nous perdrions l'avantage des compte gitlab.com déjà existant pour nos utilisateurs

**Comment by phileas-condemine** [comment]
Je suis d'accord, un argument supplémentaire est que l'incubateur des ministères sociaux utilise gitlab _on premise_.

**Comment by pajachiet** [comment]
Informations complémentaires reçues par ailleurs : 

- Si nous étions sur gitlab.com, nous pourrions (très facilement) avoir un mirroir en lecture seule sur GitHub pour la visibilité. C'est par exemple ce que fait le [projet KDE](https://community.kde.org/Infrastructure/Github_Mirror) (dans un contexte plus complexe).

- le Ministère de l'Économie et des Finances a déployé une instance Gitlab (fermée) sur le Réseau Interministériel de l'Etat. C'est un autre exemple d'adoption dans les administrations

- Pour un IDE web sur github, il y a https://medium.com/gitpod/gitpod-gitpod-online-ide-for-github-6296b907a886 C'est une bonne illustration de service externe pour GitHub, intégré dans GitLab. Il est sans doute d'excellente qualité, mais introduit une complexité pour l'utilisateur.

**Comment by strayMat** [comment]
Il peut sembler pertinent de passer à gitlab si cela permet d'améliorer l'interopérabilité entre différents environnements privés qui ne peuvent pas posséder de github. Typiquement des bulles offline comme le serveur bigdata (bigoudi) de la drees ou le futur hub ne pourront pas avoir github mais auront un gitlab. 
Le seul risque que je vois c'est de déranger des utilisateurs habitués à l'interface de github (que je trouve aussi plus sympa que gitlab). Mais la plupart du temps, ces utilisateurs sont habitués à changer d'environnement donc cela ne devrait pas trop poser de problème.

**Comment by pajachiet** [comment]
Arguments complémentaires
- GitLab a des comptes "privés" gratuits, là où GitHub est rapidement payant. Ce n'est pas un critère pour ce projet, mais peut l'être pour d'autres, et donc favoriser le choix.

- GitHub rend les CSV comme des tables que l'on peut filtrer dynamiquement. 
Nous pouvons par ailleurs le faire dynamiquement sur le site / dictionnaire, mais cela peut toujours être utile.
  - exemple https://github.com/indsante/dico-snds/blob/master/app/app_data/snds_tables.csv#L4
  - explication https://help.github.com/en/articles/rendering-csv-and-tsv-data

GitLab n'a pas cette fonctionnalité. Il faut voter sur cette issue pour que ça monte dans la pile des priorités :) https://gitlab.com/gitlab-org/gitlab-ce/issues/5947

**Comment by Izmar** [comment]
la DINSIC m'informe que :
-          Min Education nationale dispose d'une instance gitlab sur son infrastructure
-          DGFIP dispose aussi d'une instance gitlab sur son infrastructure et a un projet d’ouverture

**Comment by pajachiet** [comment]
Merci à tous pour cette discussion. 

Un dernier argument pour GitLab est que l'édition web est très pratique pour l'édition de fichiers json, ce qui facilitera grandement l'édition collaborative du schéma formel du SNDS.

Décision a été prise d'ouvrir un groupe sur gitlab.com [https://gitlab.com/healthdatahub](https://gitlab.com/healthdatahub) 

Nous allons procéder à la migration, et ne laisser que quelques répertoires en miroir sur cette organiation GitHub.
