### ISSUE TITLE
Refonte des templates de bug et features de gitlab en français

### ISSUE THREAD

**Issue by pajachiet** [indsante/Documentation-SNDS#2]
Les templates de bug et features sont actuellement en anglais, et adapté à du code plutôt qu'à de la documentation.

Je propose de les refondre en français, en adaptant aux types d'issues qui nous intéressent dans le cadre de la documentation.

**Comment by pajachiet** [comment]
Proposition de PR pour résoudre l'issue #4

**Comment by strayMat** [comment]
Je clos l'issue car la PR est merged.
