### ISSUE TITLE
Le lien du schema formalisé du SNDS dans le documentation renvoie sur un espace privé

### ISSUE THREAD

**Issue by Admin-Inds** [indsante/Documentation-SNDS#22]
Lorsqu'on est sur la documentation di SNDS dans la rubrique ressources : https://documentation-snds.health-data-hub.fr/documentation/ressources.html#documents-partages-sur-cette-documentation

Le lien : https://gitlab.com/SNDS/schema-snds renvoie sur une page erreur 404 ou une page privé gitlab. 

@pajachiet est-ce que tu as une idée ?

**Comment by pajachiet** [comment]
C'est un reliquat de la documentation vers GitHub.

J'ai corrigé 2 liens dans ce commit https://github.com/indsante/Documentation-SNDS/commit/12b16c10f34fccbcead254e307b3f82cc3a22f28, directement poussé sur master.
