### ISSUE TITLE
Ajout du lien vers scansante dans la partie Ressources 

### ISSUE THREAD

**Issue by Admin-Inds** [indsante/Documentation-SNDS#26]
**Proposition**

Proposition d'ajouter un lien vers scansante.fr dans la partie "Ressources" / "Autres ressources disponibles en ligne" / avec la. 3eme ligne sur l'ATIH

**Détails**

REMPLACER
Le site de l'ATIH, pour des détails sur le PMSI, et notamment la partie information médicale.

PAR
Le site de l'ATIH, pour des détails sur le PMSI, et notamment la partie information médicale ainsi que la plateforme de restitution des données des établissements de santé

**Références**

le lien pour cette plateforme de restitution : https://www.scansante.fr

**Comment by pajachiet** [comment]
PR https://github.com/indsante/Documentation-SNDS/pull/27

Utilisation d'une liste plutôt que d'une phrase
