### ISSUE TITLE
Licence CC-by-SA non-homologuée

### ISSUE THREAD

**Issue by pajachiet** [indsante/Documentation-SNDS#3]
# Résumé du problème

La licence utilisée pour les documents dans ce répertoire est [CC-by-SA](https://creativecommons.org/licenses/by-sa/2.0/fr/).

Or cette licence ne fait pas partie de la liste des licences utilisables par les administrations https://www.data.gouv.fr/fr/licences

# Proposition de solution
Utiliser la licence ODbL, qui couvre notre besoin et est autorisée par la loi.

# Détails

La licence CC-by-SA a été choisi pour les 2 clauses
- by = attribution = obligation de citer la source lors des réutilisations
- SA = Share Alike = obligation de partager les modifications à l'identique

L'objectif du SA est de créer un bien commun, ou tous les acteurs contribuent.

La loi propose 2 licence
- La licence ouverte, qui contient la clause d'attribution, mais pas de partage à l'identique
- La licence ODbL qui contient ces 2 clauses (cf [wikipedia](https://fr.wikipedia.org/wiki/Open_Database_License) par exemple).

# Plus de détails

[Cet article](https://medium.com/@cq94/odbl-ccbysa-590afd194aa6) de Christian Quest explique ces 3 licences, leurs enjeux, et la loi.

On note qu'il y a une vrai différence entre CC-by-SA et ODbL, lié au statut des oeuvres dérivées. Par exemple une carte est une oeuvre dérivée d'une base de données géographique. 

Dans le cas de la CC-by-SA, les oeuvres dérivées doivent également être partagées selon les mêmes conditions. Tandis que la licence ODbL n'a pas cette propagation aux oeuvres dérivées.

Lire l'article pour avoir une compréhension plus fine de cet enjeu. Notamment sur les problèmes que peuvent poser la CC-by-SA. De toute façon la loi nous contraint a priori à choisir une autre licence.

**Comment by pajachiet** [comment]
Quelques précisions 
- Ce répertoire contient des "documents" (.ppt, .pdf, .png, etc) , partagés tels quels de façon relativement statiques, et de la documentation collaborative au format markdown. 
- La question se pose de savoir si la licence odbl est adaptée à ce type de contenus.

**Comment by bzg** [comment]
Note liminaire: il est important d'éviter la publication de document dans des formats non interopérables comme le `.ppt`. Si possible, le mieux est de publier son équivalent en `.odp`, format interopérable.

La licence ODbL doit être privilégiée, comme son nom l'indique, pour les bases de données.

Pour la documentation, la [licence Ouverte 2.0](https://www.etalab.gouv.fr/licence-ouverte-open-licence) est préférable. Donc **non**, la licence ODbL n'est pas adaptée pour ce type de contenus.

Que faire si l'on souhaite utiliser une licence plus restrictive pour la documentation (équivalente à la licence CC-by-sa) ?

1. Vérifier qu'il est légitime de vouloir ajouter des restrictions sur les réutilisations: cela ne peut se faire que pour « des motifs d'intérêt général et de façon proportionnée » (voir [Article L323-2](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=BCCCCF5B5E15C3F6CABA0952E9B5A818.tplgfr21s_3?idArticle=LEGIARTI000033219073&cidTexte=LEGITEXT000031366350&dateTexte=20190307)).

2. Si c'est le cas, et si la documentation est associée à un dépôt de code source particulier (voire partie intégrante de ce dépôt, comme cela arrive souvent), on peut publier la documentation sous la même licence que le code source.  Par exemple, si une administration publie un dépôt de code source sous GNU GPL et que la documentation est dans un répertoire `doc/` de ce même dépôt, elle sera couverte par la licence du dépôt entier (GNU GPL).

3. Si ce n'est pas le cas, publier la documentation sous licence Ouverte 2.0, qui est bien adaptée aux documents écrits et aux médias (images, sons, etc.)

Dans l'ensemble, se souvenir que la licence n'est qu'un des moyens d'inciter à la création d'une communauté de contributeurs et qu'une licence sans obligation de réciprocité n'empêche pas de mobiliser des contributeurs autour d'un contenu partagé.  Les incitations relèvent de la gouvernance du projet, la licence n'est qu'un des outils de la gouvernance.

Pour le cas présent, je recommande la licence Ouverte 2.0 pour ce dépôt.

Cette documentation explique déjà bien _comment_ contribuer mais il pourrait y avoir un préambule plus explicite sur _pourquoi_ le faire et sur l'intérêt de reverser ses contributions dans ce dépôt. Ensuite, c'est en contactant les utilisateurs de la documentation que les mainteneurs du dépôt pourront les accompagner pour des contributions concrètes et partagées.

S'il y a d'autres points à éclaircir, n'hésitez pas !

**Comment by pajachiet** [comment]
Si la réponse est oui à la question 1. (légitimité d'une restriction qui force le partage à l'identique), nous serions dans un cas 2. bis non évoqué. 
En effet, la documentation n'est pas associée à un code source.

**Comment by bzg** [comment]
Oui, mais il faut prouver que ces restrictions sont nécessaires.

S'il s'agit juste de rassurer les contributeurs, il faut d'abord s'assurer qu'ils ont bien compris les enjeux autour de la distinction entre les deux grandes familles de licences.

**Comment by Admin-Inds** [comment]
Suite à notre échange avec @bzg il semblerait bien de partir sur la licence MPL 2.0 (homologuée) à réciprocité obligeant les contributions faites à être re-publiée sous MPL 2.0 au moment de leur publication. La licence : https://www.mozilla.org/en-US/MPL/2.0/ 
- La licence doit être mentionnée dans chaque fichier (fichier par fichier) mentionnant le groupe de fichiers en ajoutant une en-tête type.

**Comment by bzg** [comment]
Ces répertoires de code seront-ils dans le dépôt Documentation-SNDS ou dans d'autres dépôts ?

Dans les deux cas, c'est une possibilité, pas une obligation, mais c'est plus simple et plus lisible de n'avoir qu'une licence par dépôt.

**Comment by bzg** [comment]
Oui, le plus simple est que les dépôts de code utilisent aussi la MPL 2.0 si des lignes de ces dépôts sont copiées dans la documentation. Pour les jeux de données, soit ODbL soit licence Ouverte 2.0.

**Comment by pajachiet** [comment]
Merci beaucoup pour cette solution et la PR #11 qui va avec.
Il reste à changer les licences indiqués sur les documents pour clore l'issue

**Comment by bzg** [comment]
J'ai avancé sur les en-têtes. Il faudrait vérifier que les bas de page sont bien nécessaires dans tous les fichiers `README.md`, je ne suis pas certain.

**Comment by pajachiet** [comment]
On pourrait gérer les bas de page globalement, en modifiant le thème par défaut (cf cette [issue](https://github.com/vuejs/vuepress/issues/339)). Je propose plutôt d'ouvrir une nouvelle issue à ce sujet.

Cette PR https://github.com/indsante/Documentation-SNDS/pull/15 corrige les licences sur les documents non textuels existants, et indique comment en ajouter de nouveaux. Elle devrait clore cette issue.

**Comment by Admin-Inds** [comment]
Finalisé avec la PR #15
